import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import State from 'App/Models/State'

export default class StateSeeder extends BaseSeeder {
  public static environment = ['development', 'testing']

  public async run() {
    const uniqueKey = 'iso'

    await State.updateOrCreateMany(uniqueKey, [
      {
        id: 1,
        countryId: 31,
        regionId: 1,
        name: 'Acre',
        letter: 'AC',
        iso: 12,
        isAvailable: true,
      },
      {
        id: 2,
        countryId: 31,
        regionId: 2,
        name: 'Alagoas',
        letter: 'AL',
        iso: 27,
        isAvailable: true,
      },
      {
        id: 3,
        countryId: 31,
        regionId: 1,
        name: 'Amazonas',
        letter: 'AM',
        iso: 13,
        isAvailable: true,
      },
      {
        id: 4,
        countryId: 31,
        regionId: 1,
        name: 'Amapá',
        letter: 'AP',
        iso: 16,
        isAvailable: true,
      },
      {
        id: 5,
        countryId: 31,
        regionId: 2,
        name: 'Bahia',
        letter: 'BA',
        iso: 29,
        isAvailable: true,
      },
      {
        id: 6,
        countryId: 31,
        regionId: 2,
        name: 'Ceará',
        letter: 'CE',
        iso: 23,
        isAvailable: true,
      },
      {
        id: 7,
        countryId: 31,
        regionId: 5,
        name: 'Distrito Federal',
        letter: 'DF',
        iso: 53,
        isAvailable: true,
      },
      {
        id: 8,
        countryId: 31,
        regionId: 3,
        name: 'Espírito Santo',
        letter: 'ES',
        iso: 32,
        isAvailable: true,
      },
      {
        id: 9,
        countryId: 31,
        regionId: 5,
        name: 'Goiás',
        letter: 'GO',
        iso: 52,
        isAvailable: true,
      },
      {
        id: 10,
        countryId: 31,
        regionId: 2,
        name: 'Maranhão',
        letter: 'MA',
        iso: 21,
        isAvailable: true,
      },
      {
        id: 11,
        countryId: 31,
        regionId: 3,
        name: 'Minas Gerais',
        letter: 'MG',
        iso: 31,
        isAvailable: true,
      },
      {
        id: 12,
        countryId: 31,
        regionId: 5,
        name: 'Mato Grosso do Sul',
        letter: 'MS',
        iso: 50,
        isAvailable: true,
      },
      {
        id: 13,
        countryId: 31,
        regionId: 5,
        name: 'Mato Grosso',
        letter: 'MT',
        iso: 51,
        isAvailable: true,
      },
      {
        id: 14,
        countryId: 31,
        regionId: 1,
        name: 'Pará',
        letter: 'PA',
        iso: 15,
        isAvailable: true,
      },
      {
        id: 15,
        countryId: 31,
        regionId: 2,
        name: 'Paraiba',
        letter: 'PB',
        iso: 25,
        isAvailable: true,
      },
      {
        id: 16,
        countryId: 31,
        regionId: 2,
        name: 'Pernambuco',
        letter: 'PE',
        iso: 26,
        isAvailable: true,
      },
      {
        id: 17,
        countryId: 31,
        regionId: 2,
        name: 'Piauí',
        letter: 'PI',
        iso: 22,
        isAvailable: true,
      },
      {
        id: 18,
        countryId: 31,
        regionId: 4,
        name: 'Paraná',
        letter: 'PR',
        iso: 41,
        isAvailable: true,
      },
      {
        id: 19,
        countryId: 31,
        regionId: 3,
        name: 'Rio de Janeiro',
        letter: 'RJ',
        iso: 33,
        isAvailable: true,
      },
      {
        id: 20,
        countryId: 31,
        regionId: 2,
        name: 'Rio Grande do Norte',
        letter: 'RN',
        iso: 24,
        isAvailable: true,
      },
      {
        id: 21,
        countryId: 31,
        regionId: 1,
        name: 'Rondônia',
        letter: 'RO',
        iso: 11,
        isAvailable: true,
      },
      {
        id: 22,
        countryId: 31,
        regionId: 1,
        name: 'Roraima',
        letter: 'RR',
        iso: 14,
        isAvailable: true,
      },
      {
        id: 23,
        countryId: 31,
        regionId: 4,
        name: 'Rio Grande do Sul',
        letter: 'RS',
        iso: 43,
        isAvailable: true,
      },
      {
        id: 24,
        countryId: 31,
        regionId: 4,
        name: 'Santa Catarina',
        letter: 'SC',
        iso: 42,
        isAvailable: true,
      },
      {
        id: 25,
        countryId: 31,
        regionId: 2,
        name: 'Sergipe',
        letter: 'SE',
        iso: 28,
        isAvailable: true,
      },
      {
        id: 26,
        countryId: 31,
        regionId: 3,
        name: 'São Paulo',
        letter: 'SP',
        iso: 35,
        isAvailable: true,
      },
      {
        id: 27,
        countryId: 31,
        regionId: 1,
        name: 'Tocantins',
        letter: 'TO',
        iso: 17,
        isAvailable: true,
      },
    ])
  }
}
